### ISSUE TITLE
New `Waker`s are incorrectly ignored

### ISSUE THREAD

**Issue by SabrinaJewson** [ardaku/whisk#1]
The future contract is such that:
* When `poll` is called multiple times, the wakers are not guaranteed to be the same.
* Waking a waker from an old call to `poll` may not have any effect.
* If you return `Poll::Ready` from `poll`, the waker you have is basically completely worthless.
* If you return `Poll::Pending` from `poll`, but have not woken or cloned the waker given to you in that `poll` call's `cx.waker()`, you may wait forever.

This crate makes many assumptions about how the caller gives its futures wakers that do not hold under `Future`'s contract. This means that it's possible that perfectly valid executor implementations would leave this crate's futures hanging forever. What you need to do is _update_ the stored waker each time `poll` is called. Be careful about data races though, storing a new waker is not atomic so you'll have to use additional atomics to synchronize it.

**Comment by AldaronLau** [comment]
@SabrinaJewson thanks, I'll look into fixing this.
