### ISSUE TITLE
Avoid implementing `Future` directly on `Commander` and `Messenger`

### ISSUE THREAD

**Issue by SabrinaJewson** [ardaku/whisk#2]
`Future` types are not really meant to be `.await`ed more than once. Rust does technically allow it, but it makes for a counterintuitive and abnormal API. Additionally, `(&mut commander).await` looks worse IMO than something like `commander.next().await` or `commander.recv().await`.

I suggest to either implement [`Stream`](https://docs.rs/futures-core/latest/futures_core/stream/trait.Stream.html) which has the exact semantics that you want from the current `Future` implementation, or to provide an `async fn recv(&mut self)` instead.

**Comment by AldaronLau** [comment]
@SabrinaJewson thanks, I suppose it is a bit awkward!  I think I'll go with implementing `Stream`, despite adding a dependency (since I should be able to remove it in the future: https://doc.rust-lang.org/std/stream/trait.Stream.html).
